---
title: "Untitled"
output: html_document
---

```{r}
library(igraph)
library(ggraph)
library(dplyr)
library(readr)
library(sna)
library(igraph)
f<-file.choose()

krebs_tech = read_csv('~/Downloads/krebs_tech.csv')
krebs_tech = as.matrix(krebs_tech)
rownames(krebs_tech) <- krebs_tech[, 1] ## set rownames
krebs_tech <- krebs_tech[, -1] 

g <- graph.adjacency(krebs_tech, mode = "directed",
weighted=NULL, diag=FALSE)


image_m = data.frame(
  Block_1 = c(0,0,0,1,1),
  Block_2 = c(0,0,0,1,1),
  Block_3 = c(0,0,1,0,1),
  Block_4 = c(0,1,0,1,0),
  Block_5 = c(0,1,0,0,0), row.names = c("Block 1", "Block 2","Block 3","Block 4","Block 5")
    )

```

```{r}
library(igraph)
library(ggraph)
library(dplyr)
library(readr)
library(sna)

krebs_tech = read_csv('~/Downloads/krebs_tech.csv')
krebs_tech = as.matrix(krebs_tech)
rownames(krebs_tech) <- krebs_tech[, 1] ## set rownames
krebs_tech <- krebs_tech[, -1] 


g <- graph.adjacency(krebs_tech, mode = "directed",
weighted=NULL, diag=FALSE)

coreness(g)
kcores(g)
```

```{r}
kc<-kcores(krebs_tech, mode = "digraph", diag = FALSE, cmode = "freeman", ignore.eval = FALSE)

V(g)$kcores = kc

# plot
set.seed(1)
plot(g, vertex.size=10, vertex.label.cex=0.7, vertex.color=V(g)$kcores, vertex.frame.color=V(g)$kcores, vertex.label.color= "black", layout = layout.kamada.kawai(g), edge.arrow.size=0.3, edge.curved=seq(0, 0, length = ecount(g)), main='k-cores')
```

```{r}
names_k5 = names(kc)[kc ==5]

krebs_tech = read_csv('~/Downloads/krebs_tech.csv')
krebs_tech = as.matrix(krebs_tech)
rownames(krebs_tech) <- krebs_tech[, 1] ## set rownames
krebs_tech <- krebs_tech[, -1] 



colnames(krebs_tech)[colnames(krebs_tech) %in% names_k5] = "kcore5"
rownames(krebs_tech)[rownames(krebs_tech) %in% names_k5] = "kcore5"
colnames(krebs_tech)[colnames(krebs_tech) == "kcore5"]
df = as.data.frame(krebs_tech)
df = df[ , order(names(df))]


g <- graph.adjacency(krebs_tech, mode = "directed",
weighted=NULL, diag=FALSE)

plot(g)
```


```{r}
write.csv(df, "~/krebs_tech_kcore.csv")
```
```{r}
krebs_tech = read_csv(url("https://docs.google.com/spreadsheets/d/e/2PACX-1vRt4Xn_csjpYuQ0OHBdP3Vkot0Yr4pVCyFB9GxTwPABflRb1hFuFr3FbZQr4Cx3uYyS4kyOkPyZqUNc/pub?gid=225316930&single=true&output=csv"))

krebs_tech = as.matrix(krebs_tech)
rownames(krebs_tech) <- krebs_tech[, 1] ## set rownames
krebs_tech <- krebs_tech[, -1] 


g <- graph.adjacency(krebs_tech, mode = "directed",
weighted=NULL, diag=FALSE)
plot(g)
```
```{r}
kcores_new = kc[kc !=5]
kcores_new = c(kcores_new, "kcore5"=5)
V(g)$kcores_new = kcores_new

# plot
set.seed(1)
plot(g, vertex.size=10, vertex.label.cex=0.7, vertex.color="#2498e8", vertex.frame.color="#2498e8", vertex.label.color= "black", layout = layout.kamada.kawai(g), edge.arrow.size=0.3, edge.curved=seq(0, 0, length = ecount(g)), main='Multiplicative coreness')
kcores
```


```{r}
V(g)$Betweenness = igraph::betweenness(g)
E(g)$E_Betweenness = igraph::edge_betweenness(g)
V(g)$Closeness = igraph::closeness(g)
library(info.centrality)
V(g)$Info = info.centrality.vertex(g)


summary(V(g)$Betweenness)
summary(V(g)$Closeness)
summary(V(g)$Info)
```

```{r}
l = layout_nicely(g)
set.seed(250)
plot(g, 
vertex.color="#2498e8", vertex.frame.color="#2498e8",
vertex.size=abs(V(g)$Betweenness)*0.1,
layout = layout.kamada.kawai(g), edge.arrow.size=0.3, edge.curved=seq(0, 0, length = ecount(g)), mode="directed")
```

```{r}
l = layout_nicely(g)
set.seed(250)
plot(g, 
vertex.color="#2498e8", vertex.frame.color="#2498e8",
vertex.size=abs(V(g)$Info)*100,
layout = layout.kamada.kawai(g), edge.arrow.size=0.3, edge.curved=seq(0, 0, length = ecount(g)), mode="directed")
```

```{r}
l = layout_nicely(g)
set.seed(250)
plot(g, 
vertex.color="#2498e8", vertex.frame.color="#2498e8",
vertex.size=abs(V(g)$Closeness)*2000,
layout = layout.kamada.kawai(g), edge.arrow.size=0.3, edge.curved=seq(0, 0, length = ecount(g)), mode="directed")
```

#Меры централизации

##Degree Centralization

Метрика для сети и для идеальной сети: 

```{r echo=FALSE, warning=FALSE}
degr_cent = centr_degree(g, mode = "total", loops = TRUE, normalized = TRUE)
degr_cent$centralization # получаем значение для сети
degr_cent$theoretical_max # значение для идеальной сети с таким же кол-вом узлов и ребер
```

##Information Centralization

Метрика для сети:

```{r echo=FALSE, warning=FALSE}
library(info.centrality)
info_cent = info.centrality.vertex(g)
centralize(info_cent, normalized = FALSE)
```

##Closeness Centralization

Метрика для сети и для идеальной сети: 

```{r echo=FALSE, warning=FALSE}
close_cent = centralization.closeness(g, mode = "total", normalized = TRUE)
close_cent$centralization
close_cent$theoretical_max
```


##Betweenness Centralization

Метрика для сети и для идеальной сети: 

```{r echo=FALSE, warning=FALSE}
node_cent = centralization.betweenness(g)
node_cent$centralization
node_cent$theoretical_max
```


##Edge betweenness Centralization

Метрика для сети: 

```{r echo=FALSE, warning=FALSE}
edge_btw = edge_betweenness(df.g, e = E(df.g), directed = FALSE, weights = NULL)
edge_cent = centralize(edge_btw, normalized = FALSE)
edge_cent # не нормализованные значения
```


```{r}
library(igraph)
library(ggraph)
library(dplyr)
library(readr)
library(sna)
install.packages("ITNr")
library(ITNr)
krebs_tech = read_csv('~/Downloads/krebs_tech.csv')
krebs_tech = as.matrix(krebs_tech)
rownames(krebs_tech) <- krebs_tech[, 1] ## set rownames
krebs_tech <- krebs_tech[, -1] 
g <- graph.adjacency(krebs_tech, mode = "directed",
weighted=TRUE, diag=FALSE)

cp = core_periphery_weighted(g, "directed")[[1]]

V(cp)$color <- ifelse(V(cp)$all_cp==1, "red", "#D1D1D1")
plot(cp, vertex.size=10, vertex.label.cex=0.7, vertex.color=V(cp)$color, vertex.frame.color=V(cp)$color, vertex.label.color= "black", layout = layout.kamada.kawai(cp), edge.arrow.size=0.3, edge.curved=seq(0, 0, length = ecount(cp)), main='k-cores')
```


